package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

const maxConfigBackups = 3

type SourceConfig struct {
	Schema string   `toml:"schema" json:"schema"`
	Tables []string `toml:"tables" json:"tables"`
}

type Rule struct {
	Schema       string            `toml:"schema" json:"schema"`
	Table        string            `toml:"table" json:"table"`
	Index        string            `toml:"index" json:"index"`
	Type         string            `toml:"type" json:"type"`
	Parent       string            `toml:"parent,omitempty" json:"parent,omitempty"`
	ID           []string          `toml:"id,omitempty" json:"id,omitempty"`
	Filter       []string          `toml:"filter,omitempty" json:"filter,omitempty"`
	Pipeline     string            `toml:"pipeline,omitempty" json:"pipeline,omitempty"`
	FieldMapping map[string]string `toml:"field" json:"field"`
}

type Config struct {
	ServerID uint32 `toml:"server_id" json:"server_id"`

	MyAddr     string `toml:"my_addr" json:"my_addr"`
	MyUser     string `toml:"my_user" json:"my_user"`
	MyPassword string `toml:"my_pass" json:"my_pass"`
	MyCharset  string `toml:"my_charset,omitempty" json:"my_charset,omitempty"`

	ESHttps    bool   `toml:"es_https,omitempty" json:"es_https,omitempty"`
	ESAddr     string `toml:"es_addr" json:"es_addr"`
	ESUser     string `toml:"es_user" json:"es_user"`
	ESPassword string `toml:"es_pass" json:"es_pass"`

	DataDir  string `toml:"data_dir" json:"data_dir"`
	StatAddr string `toml:"stat_addr" json:"stat_addr"`
	StatPath string `toml:"stat_path" json:"stat_path"`
	Flavor   string `toml:"flavor" json:"flavor"`

	DumpExec       string `toml:"mysqldump,omitempty" json:"mysqldump,omitempty"`
	SkipMasterData bool   `toml:"skip_master_data,omitempty" json:"skip_master_data,omitempty"`
	BulkSize       int    `toml:"bulk_size,omitempty" json:"bulk_size,omitempty"`
	SkipNoPkTable  bool   `toml:"skip_no_pk_table,omitempty" json:"skip_no_pk_table,omitempty"`

	Sources []SourceConfig `toml:"source" json:"source"`
	Rules   []*Rule        `toml:"rule" json:"rule"`
}

type BackupInfo struct {
	Name    string `json:"name"`
	Path    string `json:"path"`
	Slot    int    `json:"slot"`
	Size    int64  `json:"size"`
	ModTime string `json:"mod_time"`
}

func loadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c Config
	if _, err := toml.Decode(string(data), &c); err != nil {
		return nil, err
	}
	for _, r := range c.Rules {
		if r.FieldMapping == nil {
			r.FieldMapping = map[string]string{}
		}
	}
	return &c, nil
}

func saveConfig(path string, c *Config) (string, error) {
	if c.Sources == nil {
		c.Sources = []SourceConfig{}
	}
	if c.Rules == nil {
		c.Rules = []*Rule{}
	}
	for _, r := range c.Rules {
		if r.FieldMapping == nil {
			r.FieldMapping = map[string]string{}
		}
		if r.Type == "" {
			r.Type = "_doc"
		}
	}

	// Keep [[source]] in sync with [[rule]] so new tables are usable immediately.
	syncSourcesFromRules(c)

	var buf bytes.Buffer
	buf.WriteString("# Generated by river-admin UI. Comments from the previous file may be replaced.\n")
	buf.WriteString("# JSON path keys in [rule.field] must be quoted, e.g. \"ext.sku\" = \"sku\"\n\n")

	enc := toml.NewEncoder(&buf)
	enc.Indent = ""
	if err := enc.Encode(c); err != nil {
		return "", err
	}

	backupNote, err := rotateConfigBackup(path)
	if err != nil {
		return "", fmt.Errorf("备份原配置失败: %w", err)
	}

	if err := writeConfigBytes(path, buf.Bytes()); err != nil {
		return "", err
	}
	return backupNote, nil
}

// saveConfigRaw writes user-provided TOML bytes after validation + backup.
// Content is written as-is (no re-encode) so comments/layout are preserved.
func saveConfigRaw(path string, data []byte) (string, error) {
	var c Config
	if _, err := toml.Decode(string(data), &c); err != nil {
		return "", fmt.Errorf("TOML 解析失败: %w", err)
	}
	if c.MyAddr == "" || c.ESAddr == "" {
		return "", fmt.Errorf("配置缺少 my_addr 或 es_addr")
	}
	backupNote, err := rotateConfigBackup(path)
	if err != nil {
		return "", fmt.Errorf("备份原配置失败: %w", err)
	}
	if err := writeConfigBytes(path, data); err != nil {
		return "", err
	}
	return backupNote, nil
}

func writeConfigBytes(path string, data []byte) error {
	// Prefer atomic rename; Docker single-file bind mounts often return
	// "device or resource busy" on rename, so fall back to in-place write.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return os.WriteFile(path, data, 0644)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return os.WriteFile(path, data, 0644)
	}
	return nil
}

func masterInfoPath(dataDir string) string {
	dir := strings.TrimSpace(dataDir)
	if dir == "" {
		dir = "/app/var"
	}
	return filepath.Join(filepath.Clean(dir), "master.info")
}

func syncStateFromConfig(c *Config) (dataDir string, masterPath string, hasMaster bool) {
	dataDir = strings.TrimSpace(c.DataDir)
	if dataDir == "" {
		dataDir = "/app/var"
	}
	masterPath = masterInfoPath(dataDir)
	_, err := os.Stat(masterPath)
	hasMaster = err == nil
	return dataDir, masterPath, hasMaster
}

func clearMasterInfo(dataDir string) (string, error) {
	p := masterInfoPath(dataDir)
	// Only allow deleting a file named master.info under the configured data_dir.
	if filepath.Base(p) != "master.info" {
		return "", fmt.Errorf("拒绝删除非 master.info 路径")
	}
	if err := os.Remove(p); err != nil {
		if os.IsNotExist(err) {
			return p, nil
		}
		return p, err
	}
	return p, nil
}

// rotateConfigBackup keeps up to 3 previous versions:
//
//	river.toml.bak.1 = newest backup (content before this save)
//	river.toml.bak.2
//	river.toml.bak.3 = oldest
func rotateConfigBackup(path string) (string, error) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return "原配置不存在，未创建备份", nil
		}
		return "", err
	}

	dir := filepath.Dir(path)
	base := filepath.Base(path)
	bak := func(n int) string {
		return filepath.Join(dir, fmt.Sprintf("%s.bak.%d", base, n))
	}

	// Drop oldest.
	_ = os.Remove(bak(maxConfigBackups))
	// Shift bak.(n) -> bak.(n+1)
	for i := maxConfigBackups - 1; i >= 1; i-- {
		src, dst := bak(i), bak(i+1)
		if _, err := os.Stat(src); err != nil {
			continue
		}
		_ = os.Remove(dst)
		if err := os.Rename(src, dst); err != nil {
			// Cross-device / busy: copy then remove
			if err2 := copyFile(src, dst); err2 != nil {
				return "", err2
			}
			_ = os.Remove(src)
		}
	}

	// Current file -> bak.1
	if err := copyFile(path, bak(1)); err != nil {
		return "", err
	}
	return fmt.Sprintf("已备份原配置为 %s.bak.1（最多保留 %d 个版本）", base, maxConfigBackups), nil
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0644)
}

func listConfigBackups(path string) ([]BackupInfo, error) {
	dir := filepath.Dir(path)
	base := filepath.Base(path)
	out := make([]BackupInfo, 0, maxConfigBackups)
	for i := 1; i <= maxConfigBackups; i++ {
		name := fmt.Sprintf("%s.bak.%d", base, i)
		p := filepath.Join(dir, name)
		st, err := os.Stat(p)
		if err != nil {
			continue
		}
		out = append(out, BackupInfo{
			Name:    name,
			Path:    p,
			Slot:    i,
			Size:    st.Size(),
			ModTime: st.ModTime().Format(time.RFC3339),
		})
	}
	return out, nil
}

// restoreConfigBackupSafe reads backup first, then rotates current, then writes.
func restoreConfigBackupSafe(path string, slot int) error {
	if slot < 1 || slot > maxConfigBackups {
		return fmt.Errorf("备份版本仅支持 1~%d", maxConfigBackups)
	}
	dir := filepath.Dir(path)
	base := filepath.Base(path)
	bakPath := filepath.Join(dir, fmt.Sprintf("%s.bak.%d", base, slot))

	data, err := os.ReadFile(bakPath)
	if err != nil {
		return fmt.Errorf("备份不存在或无法读取: %s", filepath.Base(bakPath))
	}

	if _, err := os.Stat(path); err == nil {
		if _, err := rotateConfigBackup(path); err != nil {
			return fmt.Errorf("回退前备份当前配置失败: %w", err)
		}
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return os.WriteFile(path, data, 0644)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return os.WriteFile(path, data, 0644)
	}
	return nil
}

func syncSourcesFromRules(c *Config) {
	grouped := map[string]map[string]struct{}{}
	for _, r := range c.Rules {
		if r == nil || r.Schema == "" || r.Table == "" {
			continue
		}
		if grouped[r.Schema] == nil {
			grouped[r.Schema] = map[string]struct{}{}
		}
		grouped[r.Schema][r.Table] = struct{}{}
	}

	schemas := make([]string, 0, len(grouped))
	for s := range grouped {
		schemas = append(schemas, s)
	}
	sort.Strings(schemas)

	sources := make([]SourceConfig, 0, len(schemas))
	for _, s := range schemas {
		tables := make([]string, 0, len(grouped[s]))
		for t := range grouped[s] {
			tables = append(tables, t)
		}
		sort.Strings(tables)
		sources = append(sources, SourceConfig{Schema: s, Tables: tables})
	}
	c.Sources = sources
}

func mysqlDSN(c *Config) string {
	charset := c.MyCharset
	if charset == "" {
		charset = "utf8mb4"
	}
	// my_addr is host:port
	return fmt.Sprintf("%s:%s@tcp(%s)/?charset=%s&parseTime=true&loc=Local",
		c.MyUser, c.MyPassword, c.MyAddr, charset)
}

func quoteIdent(name string) string {
	return "`" + strings.ReplaceAll(name, "`", "``") + "`"
}
